### ISSUE TITLE
Archive-Azur-Lane-Scripts-Autopatcher 

### ISSUE THREAD

**Issue by lkq13905940077** [k0np4ku/al-tools#2]
Archive-Azur-Lane-Scripts-Autopatcher v3.xx,how to do can i use it

**Comment by k0np4ku** [comment]
Drag & drop `scripts32` into `Azurlane32.exe` or `scripts64` into `Azurlane64.exe`. The default `skin.ini` is for _Japanese version_ of the game, and will be _automatically generated_ if there's a new entry. You should delete it and let the autopatcher generate a new `skin.ini` if the scripts file is not from the Japanese version of the game.

**Skin.ini description**
Plus marks means to enable (+),
Minus marks means to disable (-).
Each entry only allows one plus mark
