### ISSUE TITLE
sorry for bothering you, i have a problem when i decrypt lua files.

### ISSUE THREAD

**Issue by mikuyourworld** [k0np4ku/al-tools#3]
when i try to use this tool or autopatcher to edit scripts files manually.
I follow the instruction, decrypt scipts, unpack it.

the first two steps went well, but when i try to decrypt lua files, it always show the files were decrypted already, but i did not done this before.

**Comment by mikuyourworld** [comment]
sorry for another question. it seems even if i did not decrypt the lua files, they can be decompiled.

at last, i can patch the scripts file if i use autopatcher automatically.

**Comment by k0np4ku** [comment]
As of latest update of the game, scripts' lua files are no longer encrypted. So you can skip the decryption process.

**Comment by mikuyourworld** [comment]
Oh, I see. Thank you for answering me.
